name: Validate with hassfest

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v3"
        - uses: "home-assistant/actions/hassfest@master"
        - uses: "hacs/action@main"
          with:
            category: "integration"
